@host=http://localhost:5242

GET {{host}}/Dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZDYzYWI1Yy1lZjk4LTQyNWEtOTIyZi01YWQ0YTYyNDkwM2YiLCJnaXZlbl9uYW1lIjoiQW50b25pbyIsImZhbWlseV9uYW1lIjoiTWVkaW5hIiwianRpIjoiZWY0ZDIxYmEtYWI3My00NGVmLTkxMTItZTdhNjdiMGYyZmZmIiwiZXhwIjoxNzI0MTY4ODY4LCJpc3MiOiJNSFRlc3RlciIsImF1ZCI6Ik1IVGVzdGVyIn0.k6PAzL10B8jRDQzvMf14QxnEeiFE7xFLBq8hBIpf5tE